name: VPS SSHX 24/7 + Pterodactyl + Ngrok Feito por root@apolinario junto com SubhanPlays

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  root_apolinario:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Inicia VPS temporária via SSHX
      - name: Iniciando VPS temporária (sshx.io)
        run: curl -sSf https://sshx.io/get | sh -s run &

      # 2️⃣ Configura Docker
      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Subir PufferPanel
      - name: Instalando O Pterodactyl Painel + Pterodactyl Wings
        run: |
          apt update
          apt install -y curl docker-compose

      # 3️⃣ Subir PufferPanel
      - name: Instalando O Pterodactyl Painel + Pterodactyl Wings
        run: |
          bash <(curl -s https://raw.githubusercontent.com/Subhanplays/Pterodacrtyl-panel/main/panel)
          bash <(curl -s https://raw.githubusercontent.com/Subhanplays/Pterodacrtyl-panel/main/wings)

      # Criar usuário admin
      - name: Criar usuário admin
        run: |
          docker-compose run --rm panel php artisan p:user:make

      # Instalar Ngrok
      - name: Instalar Ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      # 7️⃣ Configurar token Ngrok
      - name: Configurar Ngrok
        run: |
          ngrok config add-authtoken 32HyO7x8z5jGhLdUR2ts0DVrD3K_2dUKsZr5rseHaRAXxz5Sf

      # 8️⃣ Expor painel PufferPanel via Ngrok
      - name: Expor Pterodactyl na web com Ngrok
        run: |
          nohup ngrok http 80 --log=stdout > ngrok.log 2>&1 &
          sleep 5
          echo "🌍 URL do Pterodactyl:"
          cat ngrok.log | grep -o "https://[a-z0-9-]*\.ngrok-free\.app" | head -n 1

      # 9️⃣ Manter job ativo (24/7 temporário)
      - name: Manter job ativo
        run: tail -f /dev/null
